server:
  port: 8001

########################## mybatis-plus 配置 ##########################
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml, classpath:mapper/**/*.xml

########################## mybatis-plus 配置 ##########################

spring:
  profiles:
    active: mysql
  application:
    name: distributed-crm







########################## eureka注册中心配置 ##########################
eureka:
  client:  #客户端注册进eureka服务列表内
    serviceUrl:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: distributed-crm
    prefer-ip-address: true  # 访问路径可以显示IP地址

