server:
  port: 7001


eureka:
  instance:
#    hostname: localhost     # eureka服务端的实例名称
    hostname: eureka1     # eureka服务端的实例名称,集群需要做端口映射,此为映射后的name
  client:
    register-with-eureka: false   # false表示不向注册中心注册自己。
    fetch-registry: false         # false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/        #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。(单机版)
#以下为集群设置,需要将其他兄弟的服务地址关联到一起。
      defaultZone: http://eureka2:7002/eureka/,http://eureka3:7003/eureka/