########################## druid 连接池(数据库)配置 ##########################
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: org.gjt.mm.mysql.Driver
#    url: jdbc:mysql://127.0.0.1:3306/db_01?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 配置打印带参数的sql
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/db_01?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid: # 以下参数针对每个库可以重新设置druid参数
      initial-size: 3
      validation-query: select 1 FROM DUAL
      max-active: 20
      min-idle: 0
      max-wait: 60000